<?php
$data = array (
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '用品分类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '7',
    'name' => '用品分类',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '健身附属品',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '20',
    'name' => '健身附属品',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '维他命',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '17',
    'name' => '维他命',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '运动营养品',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '运动营养品',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '健身设备',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '21',
    'name' => '健身设备',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '个人护理',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '18',
    'name' => '个人护理',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '饮食和体重',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '15',
    'name' => '饮食和体重',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '蛋白质',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '16',
    'name' => '蛋白质',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '品牌',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '8',
    'name' => '品牌',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '欧普特蒙',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '欧普特蒙',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => 'BSN',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '23',
    'name' => 'BSN',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '肌肉科技',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '22',
    'name' => '肌肉科技',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '目标',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => '3',
    'level' => 0,
    'id' => '6',
    'name' => '目标',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '增加肌肉',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '1',
    'name' => '增加肌肉',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '提高能力',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 3,
    'level' => 1,
    'id' => '11',
    'name' => '提高能力',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '减少体脂',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '2',
    'name' => '减少体脂',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '健康与养生',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '12',
    'name' => '健康与养生',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '提升耐力',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => '提升耐力',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '运动技能提高',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 7,
    'level' => 1,
    'id' => '10',
    'name' => '运动技能提高',
  ),
);
?>